# Generated by Django 4.2.7 on 2023-11-29 17:43

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_add_custumizedUser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(blank=True, default='Anonymous user', max_length=50, verbose_name='ユーザー名')),
                ('introduction', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='自己PR')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=account.models.upload_image_to, verbose_name='アイコン画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
